### PR TITLE
updated to use expiring-map

### PR DESCRIPTION
**Pull request by yogthos**

### CODE REVIEW

**Comment by yogthos** [comment]
Since the expiring-map does appear to be faster than core.cache I don't think there's any reason not to switch.

**Comment by boechat107** [comment]
I'm sorry @yogthos. I was coding and I didn't see this PR.

I thought about keeping `core-cache` as an option because I'm planning to change its code a bit to make some tests and, perhaps, submitting a PR to the project. However, the performance tests with `expiring-map` were so good that it will be hard for `core.cache` to compete.

**Comment by yogthos** [comment]
The other thing to consider is that core.cache doesn't provide support for stuff like listeners, so it would be tricky to provide a consistent api against both. I'd like to get this out sooner than later so that I can update luminus for better performance. :)

**Comment by yogthos** [comment]
I'd especially like this in `(em/expiring-map ttl (merge {:expiration-policy :access} opts))` so that all expiry-map options can be used, such as creation based expiry and listeners.

**Comment by boechat107** [comment]
Done!  ;-)

**Comment by yogthos** [comment]
:+1:

**Pull request closed without merging**
