### PR TITLE
moved warn-on-reflection to dev profile

### PR DESCRIPTION
**Pull request by yogthos**

### CODE REVIEW

**Comment by boechat107** [comment]
Perfect! I'll adopt this solution for my other projects.

Thanks!

**Comment by yogthos** [comment]
if you could release the new version to clojars I can push out the new template for luminus in a bit :)

**Comment by boechat107** [comment]
Ah, OK. I'll do it.

**Comment by boechat107** [comment]
Done! I have pushed the version `0.1.1`.

**Comment by yogthos** [comment]
cool stuff! :)

**Pull request merged**
